create table if not exists public.license_keys (
  id bigint generated by default as identity primary key,
  key_hash text not null unique,
  key_hint text not null,
  days integer not null check (days > 0 and days <= 3650),
  status text not null default 'unused' check (status in ('unused', 'redeemed', 'revoked')),
  device_id text,
  redeemed_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  note text
);

create index if not exists license_keys_device_idx on public.license_keys (device_id);
alter table public.license_keys enable row level security;

create or replace function public.redeem_license(
  p_key_hash text,
  p_device_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  item public.license_keys%rowtype;
  new_expires_at timestamptz;
  seconds_left numeric;
begin
  select * into item
  from public.license_keys
  where key_hash = p_key_hash
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'message', '卡密不存在');
  end if;

  if item.status = 'revoked' then
    return jsonb_build_object('ok', false, 'message', '卡密已被撤销');
  end if;

  if item.status = 'redeemed' and item.device_id <> p_device_id then
    return jsonb_build_object('ok', false, 'message', '卡密已绑定其他设备');
  end if;

  if item.status = 'redeemed' then
    seconds_left := greatest(0, extract(epoch from (item.expires_at - now())));
    return jsonb_build_object(
      'ok', true,
      'active', seconds_left > 0,
      'expires_at', item.expires_at,
      'remaining_seconds', seconds_left,
      'message', '卡密已经兑换过'
    );
  end if;

  new_expires_at := now() + make_interval(days => item.days);
  update public.license_keys
  set status = 'redeemed',
      device_id = p_device_id,
      redeemed_at = now(),
      expires_at = new_expires_at
  where id = item.id;

  seconds_left := extract(epoch from (new_expires_at - now()));
  return jsonb_build_object(
    'ok', true,
    'active', true,
    'expires_at', new_expires_at,
    'remaining_seconds', seconds_left,
    'message', '卡密兑换成功'
  );
end;
$$;
